version: '3.2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: wpdb
       MYSQL_USER: wpadmin
       MYSQL_PASSWORD: password

   wp:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wpdb
       WORDPRESS_DB_USER: wpadmin
       WORDPRESS_DB_PASSWORD: password
     working_dir: /var/www/html
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
    db: