version: '3.5'

services:
   playphdb:
     container_name: playphdb
     image: mysql:latest
     volumes:
       - playphdb:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: playphdb
       MYSQL_USER: wpadmin
       MYSQL_PASSWORD: password

   playphwp:
     container_name: playphwp
     depends_on:
       - playphdb
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: playphdb:3306
       WORDPRESS_DB_NAME: playphdb
       WORDPRESS_DB_USER: wpadmin
       WORDPRESS_DB_PASSWORD: password
     working_dir: /var/www/html
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
    playphdb: