version: '3.3'

services:
   playdb:
     container_name: playph_db
     image: mysql:5.7
     volumes:
       - playdb:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: play
       MYSQL_USER: wpadmin
       MYSQL_PASSWORD: password

   play:
     container_name: playwp
     depends_on:
       - playdb
     image: wordpress:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: playdb:3306
       WORDPRESS_DB_NAME: play
       WORDPRESS_DB_USER: wpadmin
       WORDPRESS_DB_PASSWORD: password
     working_dir: /var/www/html
     volumes:
       - ./wp-content:/var/www/html/wp-content
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
    playdb: